import pandas as pd
import numpy as np
import plotly.graph_objects as go

# Excess Mortality Normalization by Dose
# Baseline-Normalized Excess Mortality Analysis Aligned to Vaccination Doses

# This is an atempt to rebuild r-code methode with  pyton 
# r-code see https://sars2.net/czech2.html#Excess_mortality_by_weeks_after_vaccination
# I was not successful to get the same result until now - seems to contains errors in Python input data or script logic! 
# As py can't handle big table mergs with billions of rows, I tried to use another input format as the R-code does
# The input File was generated by this script from the czech vesely raw data "C:\github\CzechFOI-DRATE\Py Scripts\G) generate interval data per person.py"

# Description:
#    This script processes individual interval data related to vaccination and deaths.
#    It calculates baseline death rates from early dose intervals, aligns post-dose 
#    intervals by week, estimates expected deaths using baseline rates, and computes 
#    excess mortality percentages by week after each dose (1 to 4). Results are visualized 
#    using Plotly and saved as an interactive HTML file.

# Input and output paths
csv_path = r"C:\CzechFOI-DRATE\intervals_per_agebin\real_interval_person_all_ages_Vesely_106_202403141131.csv"
# Alternate CSV input (commented out)
# csv_path = r"C:\CzechFOI-DRATE\intervals_per_agebin\minbias_interval_person_all_ages_Vesely_106_202403141131.csv"
OUTPUT_HTML = r"C:\CzechFOI-DRATE\Plot Results\R) EM Baseline Rate Normalization\R) EM Baseline Rate Normalization.html"

# Load data from CSV
df = pd.read_csv(csv_path)
print(f"Loaded data: {df.shape[0]} rows")

# --- Step 1: Pre-process all intervals ---
# Determine the last interval for each person (used to infer death event)
df['death_day'] = df.groupby('person_id')['end_day'].transform('max')
# Flag intervals that end at the person's death day
df['event'] = (df['end_day'] == df['death_day']).astype(int)
# Estimate month number based on interval midpoint (approximated using 30.44 days/month)
df['month'] = (((df['start_day'] + df['end_day']) / 2) / 30.44).astype(int)
# Cap age at 95 to avoid outliers, then group into 5-year age bins
df['age_capped'] = df['age'].clip(upper=95)
df['age_group'] = (df['age_capped'] // 5) * 5
# Compute number of days in each interval
df['interval_days'] = df['end_day'] - df['start_day']

# --- Step 2: Calculate baseline death rate from dose 0 and 1 intervals ---
# Filter to use only early doses (0 and 1) for baseline estimation
baseline = df[df['dose_number'] <= 1].copy()
# Aggregate total person-days and events (deaths) by month and age group
baseline_agg = baseline.groupby(['month', 'age_group'], as_index=False).agg(
    total_person_days=('interval_days', 'sum'),
    total_events=('event', 'sum')
)
# Calculate baseline death rate
baseline_agg['baseline_rate'] = (
    baseline_agg['total_events'] / baseline_agg['total_person_days']
).fillna(0)

print("Baseline death rate by month & age_group computed.")

# --- Step 3: Align weeks after each dose start ---
# Extract dose start day for each person and dose
dose_start = df[['person_id', 'dose_number', 'start_day']].copy()
dose_start = dose_start.rename(columns={'start_day': 'dose_day'})

# Filter intervals corresponding to doses 1–4
df_doses = df[df['dose_number'].isin([1, 2, 3, 4])].copy()

# Merge dose day into the dose interval dataset
df_doses = df_doses.merge(dose_start, on=['person_id', 'dose_number'], how='left')

# Calculate midpoint of interval and its offset (in days) from the dose day
df_doses['interval_mid'] = (df_doses['start_day'] + df_doses['end_day']) / 2
df_doses['relative_day'] = df_doses['interval_mid'] - df_doses['dose_day']
# Convert relative day to week number
df_doses['week'] = (df_doses['relative_day'] // 7).astype(int)

print("relative_day min/max:", df_doses['relative_day'].min(), df_doses['relative_day'].max())
print("Unique weeks:", sorted(df_doses['week'].unique()))

# --- Step 4: Merge baseline rates and calculate expected deaths ---
# Merge baseline death rates based on matching month and age group
df_doses = df_doses.merge(
    baseline_agg[['month', 'age_group', 'baseline_rate']],
    on=['month', 'age_group'],
    how='left'
)
# Drop intervals without baseline rate match
df_doses = df_doses.dropna(subset=['baseline_rate'])

# Estimate expected deaths based on baseline rate and interval length
df_doses['expected'] = df_doses['baseline_rate'] * df_doses['interval_days']

# --- Step 5: Aggregate observed and expected deaths by week & dose ---
# Group by week and dose number, aggregating observed and expected deaths
agg = df_doses.groupby(['week', 'dose_number'], as_index=False).agg(
    observed_deaths=('event', 'sum'),
    expected_deaths=('expected', 'sum'),
    person_days=('interval_days', 'sum')
)
# Compute excess mortality percentage
agg['excess_percent'] = np.where(
    agg['expected_deaths'] > 0,
    (agg['observed_deaths'] / agg['expected_deaths'] - 1) * 100,
    np.nan
)

# Suppress excess % output where sample size is too small (low reliability)
hidelim = 10_000
agg.loc[agg['person_days'] < hidelim, 'excess_percent'] = np.nan

print("Aggregated excess mortality data ready for plotting.")

# --- Step 6: Plot with Plotly ---
fig = go.Figure()
# Define dose labels and colors
dose_labels = [f"Dose {i}" for i in range(1, 5)]
colors = ['#E69F00', '#56B4E9', '#009E73', '#F0E442']

# Plot excess mortality line per dose
for i, dose in enumerate(range(1, 5)):
    sub = agg[agg['dose_number'] == dose]
    if sub.empty or sub['excess_percent'].dropna().empty:
        continue
    fig.add_trace(go.Scatter(
        x=sub['week'],
        y=sub['excess_percent'],
        mode='lines+markers',
        name=dose_labels[i],
        line=dict(color=colors[i], width=2),
        connectgaps=True,
        hovertemplate=(
            f"{dose_labels[i]}<br>Week: %{{x}}<br>"
            "Excess Mortality: %{y:.2f}%<br>"
            "Person-days: %{customdata:,.0f}"
        ),
        customdata=sub['person_days']
    ))

# Add horizontal reference line at 0% excess
fig.add_shape(
    type="line",
    x0=agg['week'].min(),
    y0=0,
    x1=agg['week'].max(),
    y1=0,
    line=dict(color="black", width=1)
)

# Define plot subtitle annotation
subtitle = (
    f"Baseline death rate uses dose ≤1 intervals, matched by age and month.<br>"
    f"Week 0 = day of dose + next 6 days.<br>"
    f"Expected deaths = baseline_rate × person-days.<br>"
    f"Weeks with fewer than {hidelim:,} person-days are hidden."
)
# Final layout adjustments
fig.update_layout(
    title={
        'text': "Excess Mortality by Weeks After Vaccination (Aligned to Dose Day)",
        'x': 0.5, 'xanchor': 'center'
    },
    xaxis=dict(title="Weeks After Vaccination", dtick=5, showgrid=True),
    yaxis=dict(title="Excess Mortality (%)", showgrid=True),
    legend_title_text="Dose",
    margin=dict(t=120, b=80),
    annotations=[dict(
        x=0, y=1.02, xref='paper', yref='paper',
        text=subtitle, showarrow=False, align='left', font=dict(size=10)
    )],
    hovermode='x unified'
)

# Save plot to HTML file
fig.write_html(OUTPUT_HTML)
print(f"Plot saved to {OUTPUT_HTML}")
# Show plot in browser
fig.show()
